import Link from "next/link";
import type { Metadata } from "next";

import { ContentPage, ContentSection } from "@/components/content-page";

export const metadata: Metadata = {
  title: "Terms",
  description:
    "The terms of service for using Ardezan — accounts, AI previews, orders, payments, and acceptable use.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <ContentPage
      eyebrow="Legal"
      title="Terms of Service"
      lastUpdated="May 2026"
      intro="By using Ardezan you agree to these terms. We’ve kept them short and readable."
    >
      <ContentSection heading="Your account">
        <p>
          You’re responsible for keeping your login secure and for activity under
          your account. You must be 18 or older to upload a photo and use the
          try-on features, and you may only upload photos of yourself.
        </p>
      </ContentSection>

      <ContentSection heading="AI previews are approximations">
        <p>
          Try-on images are generated by AI to help you visualise a look. They
          are previews, not exact representations — real garments may differ in
          colour, drape, texture, and fit. Recommended sizes are suggestions;
          the final choice is yours.
        </p>
      </ContentSection>

      <ContentSection heading="Orders & payment">
        <p>
          Prices and availability can change until an order is placed. We confirm
          your order once payment succeeds. We may cancel and refund an order if
          an item is unavailable or if we detect an error or suspected fraud.
        </p>
      </ContentSection>

      <ContentSection heading="Returns">
        <p>
          Returns and exchanges are covered on our{" "}
          <Link className="underline underline-offset-2" href="/returns">
            returns page
          </Link>
          .
        </p>
      </ContentSection>

      <ContentSection heading="Acceptable use">
        <p>
          Don’t upload photos of other people without their consent, don’t
          attempt to misuse or overload the service, and don’t use the AI to
          generate harmful or unlawful content. We may suspend accounts that
          break these rules.
        </p>
      </ContentSection>

      <ContentSection heading="Liability">
        <p>
          The service is provided “as is.” To the extent permitted by law,
          Ardezan isn’t liable for indirect or incidental damages arising from
          use of the service or reliance on AI previews.
        </p>
      </ContentSection>

      <ContentSection heading="Changes">
        <p>
          We may update these terms; continued use after an update means you
          accept the revised terms. The “last updated” date above reflects the
          current version.
        </p>
      </ContentSection>
    </ContentPage>
  );
}
