/**
 * Curated Design Me starting points.
 *
 * Used in two places:
 * - ``/try-on/design`` renders them as an "Inspiration" gallery above
 *   the form. Tapping a tile pre-fills the form.
 * - ``/catalog?cat=bespoke`` renders them as a product-grid showcase
 *   for customers browsing the catalog. Each card deep-links into
 *   ``/try-on/design`` with ``?inspiration=<id>`` so the form starts
 *   already filled in.
 *
 * Each entry pairs a fabric (from the seeded library) with a piece and
 * a tested brief that renders well in Gemini Image.
 */
import type { Complexity, PieceType } from "@/lib/types";

export type DesignInspiration = {
  id: string;
  fabric_id: string;
  piece_type: PieceType;
  complexity: Complexity;
  title: string;
  brief: string;
  fit_note?: string;
  // Used for the Bespoke showcase tile copy — one-line marketing
  // description. Kept short on purpose; the brief is the long form.
  tagline: string;
  // Visual color family for the swatch backdrop. Falls back to the
  // fabric's gradient when not set.
  gradient?: string;
};

// AI-rendered hero photo for each inspiration. Generated by
// ``backend/scripts/render_design_showcases.py`` into
// ``frontend/public/bespoke/<id>.png`` — see that script to regenerate.
// Falling back to the fabric gradient is automatic on the consumer side.
export const INSPIRATION_IMAGES: Record<string, string> = {
  ins_linen_shirt: "/bespoke/ins_linen_shirt.png",
  ins_wool_blazer: "/bespoke/ins_wool_blazer.png",
  ins_khaki_trouser: "/bespoke/ins_khaki_trouser.png",
  ins_poplin_dress: "/bespoke/ins_poplin_dress.png",
  ins_denim_overshirt: "/bespoke/ins_denim_overshirt.png",
  ins_cashmere_coat: "/bespoke/ins_cashmere_coat.png",
  ins_kente_blazer: "/bespoke/ins_kente_blazer.png",
  ins_kente_dress: "/bespoke/ins_kente_dress.png",
  ins_ankara_wrap: "/bespoke/ins_ankara_wrap.png",
};

export const DESIGN_INSPIRATIONS: DesignInspiration[] = [
  {
    id: "ins_linen_shirt",
    fabric_id: "fab_italian_linen",
    piece_type: "shirt",
    complexity: "standard",
    title: "Camp-collar linen shirt",
    tagline: "Open-collar shirt in lightweight Italian linen.",
    brief:
      "Camp-collar shirt, short sleeves, single chest pocket, mother-of-pearl buttons. Boxy through the body.",
    fit_note: "Relaxed, falls just past the hip.",
  },
  {
    id: "ins_wool_blazer",
    fabric_id: "fab_wool_flannel",
    piece_type: "blazer",
    complexity: "intricate",
    title: "Unstructured wool blazer",
    tagline: "Single-breasted blazer in soft English wool flannel.",
    brief:
      "Single-breasted, notched lapels, two-button closure, soft shoulder, side vents, working cuffs.",
    fit_note: "Tailored at the waist, slight taper.",
  },
  {
    id: "ins_khaki_trouser",
    fabric_id: "fab_khaki_twill",
    piece_type: "trouser",
    complexity: "standard",
    title: "Pleated khaki trouser",
    tagline: "Pleated trouser cut from structured cotton twill.",
    brief:
      "Double-pleated trouser, mid-rise, side adjusters, slight taper, finished with a 1.5-inch turn-up.",
    fit_note: "Drapes cleanly without breaking on the shoe.",
  },
  {
    id: "ins_poplin_dress",
    fabric_id: "fab_cotton_poplin",
    piece_type: "dress",
    complexity: "standard",
    title: "Cotton poplin shirt-dress",
    tagline: "Button-through shirt-dress in crisp cotton poplin.",
    brief:
      "Collared shirt-dress, fitted waist with a thin self-belt, knee-length, button-through front.",
    fit_note: "Defined at the waist, A-line through the skirt.",
  },
  {
    id: "ins_denim_overshirt",
    fabric_id: "fab_japanese_denim",
    piece_type: "overshirt",
    complexity: "standard",
    title: "Japanese denim overshirt",
    tagline: "Western-yoke overshirt in selvedge Japanese denim.",
    brief:
      "Western-yoke overshirt, two chest pockets with flaps, point collar, pearl-snap closure.",
    fit_note: "Roomy through the body, fits over a sweater.",
  },
  {
    id: "ins_cashmere_coat",
    fabric_id: "fab_cashmere",
    piece_type: "coat",
    complexity: "intricate",
    title: "Cashmere overcoat",
    tagline: "Double-breasted overcoat in Italian cashmere.",
    brief:
      "Double-breasted overcoat, peak lapels, six-button closure, full lining, two flap pockets, back vent.",
    fit_note: "Falls to mid-thigh, structured shoulders.",
  },
  // ── Kente + Ankara: brand-defining pieces. ────────────────────
  {
    id: "ins_kente_blazer",
    fabric_id: "fab_kente",
    piece_type: "blazer",
    complexity: "intricate",
    title: "Hand-woven Kente blazer",
    tagline: "Tailored blazer in hand-woven Ghanaian Kente.",
    brief:
      "Single-breasted Kente blazer with notched lapels, one-button closure, plain black lapels and cuffs as a counterpoint to the woven body, double back vent.",
    fit_note: "Tailored at the waist, full canvas, padded shoulder.",
  },
  {
    id: "ins_kente_dress",
    fabric_id: "fab_kente",
    piece_type: "dress",
    complexity: "intricate",
    title: "Kente column dress",
    tagline: "Floor-length Kente dress with a strapless bodice.",
    brief:
      "Floor-length column dress, strapless sweetheart bodice, fitted through the waist and hips, side slit to mid-thigh, fully lined.",
    fit_note: "Hugs the silhouette through bodice and hip, falls clean to the floor.",
  },
  {
    id: "ins_ankara_wrap",
    fabric_id: "fab_ankara",
    piece_type: "dress",
    complexity: "standard",
    title: "Ankara wrap dress",
    tagline: "Knee-length wrap dress in Ankara wax print.",
    brief:
      "Knee-length wrap dress, deep V neckline, three-quarter sleeves, self-tie at the waist, A-line skirt.",
    fit_note: "Fitted through the bodice, gentle flare from the waist.",
  },
];

export function findInspiration(id: string | null | undefined): DesignInspiration | null {
  if (!id) return null;
  return DESIGN_INSPIRATIONS.find((i) => i.id === id) ?? null;
}

// Mirror of the swatch gradients seeded on the backend. Kept here so
// server-rendered pages (notably ``/catalog?cat=bespoke``) can render
// the showcase without an extra fetch to ``GET /fabrics``.
export const FABRIC_GRADIENTS: Record<string, { name: string; gradient: string }> = {
  fab_italian_linen: {
    name: "Italian Linen",
    gradient: "linear-gradient(135deg, #e8dcc4 0%, #d4c5a0 50%, #b8a679 100%)",
  },
  fab_wool_flannel: {
    name: "Wool Flannel",
    gradient: "linear-gradient(135deg, #5a5a5a 0%, #3e3e44 50%, #2a2a30 100%)",
  },
  fab_khaki_twill: {
    name: "Khaki Twill",
    gradient: "linear-gradient(135deg, #c8b290 0%, #a8916b 50%, #7a6647 100%)",
  },
  fab_cotton_poplin: {
    name: "Cotton Poplin",
    gradient: "linear-gradient(135deg, #ffffff 0%, #f3f3f5 50%, #dadce0 100%)",
  },
  fab_japanese_denim: {
    name: "Japanese Denim",
    gradient: "linear-gradient(135deg, #4a5a78 0%, #2e3c5a 50%, #1a2440 100%)",
  },
  fab_cashmere: {
    name: "Italian Cashmere",
    gradient: "linear-gradient(135deg, #6b4a3a 0%, #4a2e22 50%, #2e1a14 100%)",
  },
  fab_kente: {
    name: "Hand-woven Kente",
    gradient:
      "linear-gradient(135deg, #e8b923 0%, #c83a2a 30%, #1f7a3a 60%, #1c1c2e 100%)",
  },
  fab_ankara: {
    name: "Ankara Wax Print",
    gradient:
      "linear-gradient(135deg, #f4d68a 0%, #d96a1f 35%, #9d2727 65%, #1a3a8c 100%)",
  },
};
